{"uuid": "c84c19fa-56f6-493b-a632-ac66102104d2", "children": ["0148a42e-3a8d-4f27-a803-3d4f854b8efe"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114\nCurrent browser version is 116.0.5845.180 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0075A813+48355]\n\t(No symbol) [0x006EC4B1]\n\t(No symbol) [0x005F5358]\n\t(No symbol) [0x006161AC]\n\t(No symbol) [0x00611EF3]\n\t(No symbol) [0x00610579]\n\t(No symbol) [0x00640C55]\n\t(No symbol) [0x0064093C]\n\t(No symbol) [0x0063A536]\n\t(No symbol) [0x006182DC]\n\t(No symbol) [0x006193DD]\n\tGetHandleVerifier [0x009BAABD+2539405]\n\tGetHandleVerifier [0x009FA78F+2800735]\n\tGetHandleVerifier [0x009F456C+2775612]\n\tGetHandleVerifier [0x007E51E0+616112]\n\t(No symbol) [0x006F5F8C]\n\t(No symbol) [0x006F2328]\n\t(No symbol) [0x006F240B]\n\t(No symbol) [0x006E4FF7]\n\tBaseThreadInitThunk [0x768200C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77BA7B1E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77BA7AEE+238]\n\n", "trace": "  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\credence\\Parabank_pytest_project\\testcases\\conftest.py\", line 14, in setup\n    driver=webdriver.Chrome()\n           ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\rahul\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1694072397101, "stop": 1694072400970}], "start": 1694072397101, "stop": 1694072401068}